# Generated by Django 6.0.3 on 2026-05-05 23:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=1)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('nome_guerra', models.CharField(max_length=50)),
                ('numero_camisa', models.PositiveSmallIntegerField(help_text='Insira um valor entre 1 e 26', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(26)])),
                ('data_nasc', models.DateField()),
                ('suspenso', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('nacionalidade', models.CharField(max_length=100)),
                ('data_nasc', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('estadio', models.CharField(blank=True, max_length=150)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('gols_mandante', models.PositiveSmallIntegerField(default=0)),
                ('gols_visitante', models.PositiveSmallIntegerField(default=0)),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_copa.grupo')),
            ],
        ),
        migrations.CreateModel(
            name='EventoJogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minuto', models.PositiveSmallIntegerField()),
                ('acressimo', models.BooleanField(default=False)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='app_copa.jogador')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='app_copa.jogo')),
            ],
        ),
        migrations.CreateModel(
            name='Selecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=3, unique=True)),
                ('escudo', models.URLField(blank=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selecoes', to='app_copa.grupo')),
                ('tecnico', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selecao', to='app_copa.tecnico')),
            ],
        ),
        migrations.AddField(
            model_name='jogo',
            name='selecao_mandante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jogos_mandante', to='app_copa.selecao'),
        ),
        migrations.AddField(
            model_name='jogo',
            name='selecao_visitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jogos_visitante', to='app_copa.selecao'),
        ),
        migrations.AddField(
            model_name='jogador',
            name='selecao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jogadores', to='app_copa.selecao'),
        ),
    ]
