# Generated by Django 6.0.5 on 2026-05-06 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_copa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventojogo',
            name='tipo',
            field=models.CharField(choices=[('Gol', 'Gol'), ('Cartao_amarelo', 'Cartão Amarelo'), ('Cartao_vermelho', 'Cartão Vermelho'), ('Gol_contra', 'Gol Contra')], default='Gol', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jogo',
            name='fase',
            field=models.CharField(choices=[('Grupos', 'Grupos'), ('Fase 32', 'Fase 32'), ('Oitavas', 'Oitavas'), ('Quartas', 'Quartas'), ('Semifinal', 'Semifinal'), ('Final', 'Final')], default='Fase de Grupos', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jogo',
            name='status',
            field=models.CharField(choices=[('Agendado', 'Agendado'), ('Em_andamento', 'Em Andamento'), ('Encerrado', 'Encerrado'), ('Cancelado', 'Cancelado')], default='Agendado', max_length=20),
        ),
    ]
