# Generated by Django 6.0.5 on 2026-05-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_copa', '0002_eventojogo_tipo_jogo_fase_jogo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='posicao',
            field=models.CharField(choices=[('GL', 'Goleiro'), ('ZAG', 'Zagueiro'), ('LAT', 'Lateral'), ('VOL', 'Volante'), ('MC', 'Meia'), ('ATA', 'Atacante')], default='ATA', max_length=3),
            preserve_default=False,
        ),
    ]
